spring.application.name=demo

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=
spring.mail.password=

# APP BASE URL
app.url=
app.full.url=
#app.url=localhost
#app.full.url=http://localhost:8080

# PASSWORD REGEX
password.valid.regexp=^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^a-zA-Z0-9]).{8,}$

# JWT
jwt.secret=
jwt.expiration=60000

# TOTP
totp.application.time=0
totp.application.name=TOTP-Demo
totp.application.url=

# Timeout code/ token
send.code.token.timeout=60

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Facebook OAuth2 Client Configuration
spring.security.oauth2.client.registration.facebook.client-id=
spring.security.oauth2.client.registration.facebook.client-secret=


# Google OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_post


# Google OAuth2 Provider Configuration
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect